version: '3'

services:
  app:
    stdin_open: true
    tty: true

  adminer:
    image: adminer
    restart: always
    ports:
      - ${DOCKER_ADMINER_PORT:-8888}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - db
    networks:
      - db_nw


networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
